app = "threadsearch"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  THREAD_SEARCH_PUBLIC_CONTACT = "https://github.com/zvory/threadsearch/issues"
  THREAD_SEARCH_REMOVAL_REQUEST_URL = "https://github.com/zvory/threadsearch/issues"

[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
